// <auto-generated />
namespace TicketinDataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ddeswq : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ddeswq));
        
        string IMigrationMetadata.Id
        {
            get { return "202208031350125_ddeswq"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
